version: "3"

services:
  web: 
    image: soldierstark/backend:1.0
    container_name: backend
    restart: always
    build: .
    ports:
      - 8085:8085
    links: 
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: soldierstark/database:1.0
    container_name: database
    build: 
      dockerfile: ./mongo_docker/Dockerfile
    #container_name: mongodatabase
    #image: mongo
    ports: 
      - 27017:27017